version: '3.7'
services:
  custom_whisper:
    container_name: custom_whisper
    image: ghcr.io/cociweb/amd64-standalone_whisper:latest
    ports:
      - 10300:10300
    volumes:
      - custom_whisper_data:/data
    restart: always
    command: --model custom --language hu --beam-size 5 --compute-type int8 --custom_model_name "My customized Whisper Model" --custom_model_url "https://huggingface.co/Hungarians/whisper-base-cv16-v2-int8.hu/resolve/main/"
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8096M

volumes:
  custom_whisper_data:
