---
version: 1.1.0
slug: whisper
name: Custom Whisper
description: Speech-to-text with Customized Whisper
url: https://github.com/cociweb/custom_whisper/
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
backup_exclude:
  - "*.bin"
options:
  model: tiny-int8
  language: en
  beam_size: 1
  compute_type: default
  custom_model_name: null
  custom_model_url: null
schema:
  model: list(tiny-int8|tiny|base|base-int8|small-int8|small|medium-int8|custom)
  compute_type: list(default|auto|int8|int8_float32|int8_float16|int8_bfloat16|int16|float16|float32|bfloat16)
  language: |
    list(auto|af|am|ar|as|az|ba|be|bg|bn|bo|br|bs|ca|cs|cy|da|de|el|en|es|et|eu|fa|fi|fo|fr|gl|gu|ha|haw|he|hi|hr|ht|hu|hy|id|is|it|ja|jw|ka|kk|km|kn|ko|la|lb|ln|lo|lt|lv|mg|mi|mk|ml|mn|mr|ms|mt|my|ne|nl|nn|no|oc|pa|pl|ps|pt|ro|ru|sa|sd|si|sk|sl|sn|so|sq|sr|su|sv|sw|ta|te|tg|th|tk|tl|tr|tt|uk|ur|uz|vi|yi|yo|zh)
  beam_size: int
  custom_model_name: str?
  custom_model_url: str?
ports:
  "10300/tcp": null
homeassistant: 2023.9.0
image: ghcr.io/cociweb/{arch}-addon-whisper
