name: Build and Publish Add-on

on:
  push:
    branches:
      - main
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: ["custom_whisper"]
        arch: ["aarch64", "amd64"]

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.1.1

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: ./${{ matrix.addon }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACTION_TOKEN }}

      - name: Build ${{ matrix.arch }} add-on
#        if: github.event_name == 'push' && contains(github.ref, '/tags/v')
        uses: home-assistant/builder@2024.03.5
        with:
          args: |
            --${{ matrix.arch }} \
            --target ${{matrix.addon}} \
            --image "${{ matrix.arch }}-addon-whisper" \
            --docker-hub "ghcr.io/${{ github.repository_owner }}"

